"""
StudyFlow Icon System
Lucide-inspired Unicode icon map for consistent use across all modules.
Icons are rendered as text labels using Unicode characters.
"""

# ── Navigation Icons ──────────────────────────────────────────────────────────
ICONS = {
    # Navigation
    "Dashboard":       "⊞",
    "BookOpen":        "⊟",
    "ClipboardCheck":  "☑",
    "Calendar":        "▦",
    "FileText":        "≡",
    "FolderOpen":      "▢",
    "GraduationCap":   "⊙",
    "Clock3":          "◷",
    "Bell":            "⊛",
    "Settings":        "⊕",
    "UserCircle":      "⊗",
    "Plus":            "＋",
    "Pencil":          "✎",
    "Trash2":          "✕",
    "Save":            "⊠",
    "Download":        "⬇",
    "Upload":          "⬆",
    "LogOut":          "⊖",
    "Search":          "⊘",
    "Home":            "⌂",
    "ChevronRight":    "›",
    "ChevronLeft":     "‹",
    "ChevronDown":     "⌄",
    "Star":            "★",
    "Check":           "✓",
    "X":               "✕",
    "AlertTriangle":   "⚠",
    "Info":            "ℹ",
    "TrendingUp":      "↗",
    "BarChart":        "▐",
    "PieChart":        "◑",
    "BookMarked":      "⊟",
    "Layout":          "⊞",
    "Layers":          "≡",
    "Target":          "◎",
    "Zap":             "⚡",
    "Award":           "✦",
    "Activity":        "⌇",
    "Eye":             "◉",
    "Lock":            "⊛",
    "Unlock":          "⊚",
    "Link":            "⊗",
    "ExternalLink":    "↗",
    "RefreshCw":       "↺",
    "Filter":          "▽",
    "SortAsc":         "↑",
    "SortDesc":        "↓",
    "Grid":            "⊞",
    "List":            "≡",
    "Moon":            "☽",
    "Sun":             "☀",
    "Circle":          "○",
    "CircleFill":      "●",
    "Square":          "□",
    "ArrowRight":      "→",
    "ArrowLeft":       "←",
    "ArrowUp":         "↑",
    "ArrowDown":       "↓",
    "MoreHorizontal":  "⋯",
    "MoreVertical":    "⋮",
    "Flame":           "🔥",
    "Lightning":       "⚡",
    "Book":            "⊟",
    "Clipboard":       "☑",
    "Timer":           "◷",
    "User":            "⊗",
    "Users":           "⊗",
    "MessageSquare":   "☐",
    "Tag":             "⊙",
    "Bookmark":        "⊟",
    "Heart":           "♥",
    "Smile":           "☺",
    "ThumbsUp":        "↑",
}


def get_icon(name: str, fallback: str = "•") -> str:
    """Return the icon character for the given Lucide icon name."""
    return ICONS.get(name, fallback)
